unique_ids:
  assets:
    standard-page.html: TWGOL4I7YVZV3AJNFVPXTWWFIJFQ3YXI
    theme.css: NQISNLFGIAXLKNYIP56LAJ57ZVOUFTW6
  forms:
    Form1: QUPLSEJFIAAPATLZE7WFOFKFKUYYR6MQ
  modules: {}
  scripts: {}
  server_modules: {}
